### PR TITLE
fix: warn should handles all externals config

### LINKED ISSUE #142: [Bug]: should not warn when commonjs request is not external
### Details

```ts
// entry.ts
console.log(require('lib1').value);
```

```js
// lib1
module.exports.value = 'lib1 cjs'
```

When bundle esm, it will cause warning in log
image

### PR DESCRIPTION
**Pull request by fi3ework**
## Summary

Fix #142.

## Checklist

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

### CODE REVIEW

File: packages/core/src/config.ts [hunk 1]
```diff
@@ -88,6 +88,108 @@ export async function loadConfig({
...
+        ({ request, dependencyType, contextInfo }: any, callback: any) => {
+          let externalized = false;
+          const _callback = (matched?: true) => {
+            if (matched) {
+              externalized = true;
+            }
+          };
+
+          if (contextInfo.issuer && dependencyType === 'commonjs') {
+            matchUserExternals(externals, request, _callback);
```
Comment (Timeless0911) [inline packages/core/src/config.ts:181]: Why not return boolean directly insteadof using callbacl function?

Comment (fi3ework) [reply packages/core/src/config.ts:181]: It's somehow a complex logic, just to port webpack's logic and edit as less as possible.

**Review by Timeless0911 — APPROVED** [review]
